TaskManager.WebMVC/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaskManager.Core;
using TaskManager.Core.Data;
using TaskManager.Core.Data.Repositories;
using TaskManager.Core.Models;
using Microsoft.AspNetCore.Identity;

namespace TaskMaganer.Controllers
{
    public class TaskController : DefaultController
    {
        private readonly TaskRepository _taskRepository;
        private readonly TopicRepository _topicRepository;
        private readonly UserRepository _userRepository;
        private readonly UserManager<IdentityUser> _userManager;

        public TaskController(TaskManagerContext context, UserManager<IdentityUser> userManager)
        {
            _taskRepository = new TaskRepository(context);
            _topicRepository = new TopicRepository(context);
            _userRepository = new UserRepository(context);
            _userManager = userManager;
        }

        // GET: Task
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _taskRepository.ListAllAsync());
        }

        // GET: Task/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _taskRepository.GetByKeyAsync(id);
            if (task == null)
            {
                return NotFound();
            }

            // Get current user
            var user = await _userManager.GetUserAsync(User);
            

            return View(task);
        }

        // GET: Task/Create
        public async Task<IActionResult> Create()
        {
            ViewData["TopicId"] = new SelectList(await _topicRepository.ListAllAsync(), "Id", "Name");
            ViewData["UserId"] = new SelectList(await _userRepository.ListAllAsync(), "Id", "Name");
            return View();
        }

        // POST: Task/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MTask task)
        {
            var user = await _userRepository.GetByKeyAsync(task.UserId);
            var topic = await _topicRepository.GetByKeyAsync(task.TopicId);

            if (user is null || topic is null)
                return NotFound();

            task.User = user;
            task.Topic = topic;
            
            foreach (var taskSubTask in task.SubTasks)
            {
                if (taskSubTask is null)
                    continue;
                
                taskSubTask.MainTask = task;
                taskSubTask.UserId = task.UserId;
                taskSubTask.User = user;
                taskSubTask.TopicId = task.TopicId;
                taskSubTask.Topic = topic;
            }

            try
            {
                await _taskRepository.CreateAsync(task);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewData["TopicId"] = new SelectList(await _topicRepository.ListAllAsync(), "Id", "Name", task.TopicId);
                ViewData["UserId"] = new SelectList(await _userRepository.ListAllAsync(), "Id", "Name", task.UserId);
                return View(task);
            }
        }

        // GET: Task/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var task = await _taskRepository.GetByKeyAsync(id);
            if (task == null)
                return NotFound();

            ViewData["TopicId"] = new SelectList(await _topicRepository.ListAllAsync(), "Id", "Name", task.TopicId);
            ViewData["UserId"] = new SelectList(await _userRepository.ListAllAsync(), "Id", "Name", task.UserId);
            return View(task);
        }

        // POST: Task/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Title,TextContent,UserId,TopicId,Status,CreatedAt,UpdatedAt")]
            MTask task)
        {
            if (id != task.Id)
                return NotFound();

            var user = await _userRepository.GetByKeyAsync(task.UserId);
            var topic = await _topicRepository.GetByKeyAsync(task.TopicId);

            if (user is null || topic is null)
                return NotFound();

            task.User = user;
            task.Topic = topic;

            try
            {
                var existingTask = await _taskRepository.GetByKeyAsync(task.Id);

                if (existingTask == null)
                {
                    return NotFound();
                }
                
                existingTask.Title = task.Title;
                existingTask.TextContent = task.TextContent;
                existingTask.UserId = task.UserId;
                existingTask.TopicId = task.TopicId;
                existingTask.Status = task.Status; 
                existingTask.UpdatedAt = DateTime.Now; 

                await _taskRepository.UpdateAsync(existingTask);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewData["TopicId"] = new SelectList(await _topicRepository.ListAllAsync(), "Id", "Name", task.TopicId);
                ViewData["UserId"] = new SelectList(await _userRepository.ListAllAsync(), "Id", "Name", task.UserId);
                return View(task);
            }
        }

        // GET: Task/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var task = await _taskRepository.GetByKeyAsync(id);
            if (task == null)
                return NotFound();

            return View(task);
        }

        // POST: Task/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var task = await _taskRepository.GetByKeyAsync(id);
            if (task != null)
                await _taskRepository.DeleteAsync(task);

            return RedirectToAction(nameof(Index));
        }
    }
}

TaskManager.WebMVC/Controllers/TopicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Core;
using TaskManager.Core.Data;
using TaskManager.Core.Data.Repositories;
using TaskManager.Core.Enums;
using TaskManager.Core.Models;

namespace TaskMaganer.Controllers
{
    public class TopicController : DefaultController
    {
        private readonly TopicRepository _topicRepository;

        public TopicController(TaskManagerContext context)
        {
            _topicRepository = new TopicRepository(context);
        }

        // GET: Topic
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _topicRepository.ListAllAsync());
        }

        // GET: Topic/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var topic = await _topicRepository.GetByKeyAsync(id);
            if (topic == null)
                return NotFound();

            return View(topic);
        }

        // GET: Topic/Create
        
        public IActionResult Create()
        {
            ViewBag.ColorOptions = Enum.GetValues(typeof(TopicColorOptionsEnum)).Cast<TopicColorOptionsEnum>();
            return View();
        }

        // POST: Topic/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Color")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                await _topicRepository.CreateAsync(topic);
                return RedirectToAction(nameof(Index));
            }

            return View(topic);
        }

        // GET: Topic/Edit/5
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();
            
            var topic = await _topicRepository.GetByKeyAsync(id);
            if (topic == null)
                return NotFound();

            return View(topic);
        }

        // POST: Topic/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Color")] Topic topic)
        {
            if (id != topic.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                await _topicRepository.UpdateAsync(topic);
                return RedirectToAction(nameof(Index));
            }

            return View(topic);
        }

        // GET: Topic/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            
            var topic = await _topicRepository.GetByKeyAsync(id);
            if (topic == null)
                return NotFound();

            return View(topic);
        }

        // POST: Topic/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var topic = await _topicRepository.GetByKeyAsync(id);
            if (topic != null)
                await _topicRepository.DeleteAsync(topic);
            
            return RedirectToAction(nameof(Index));
        }
    }
}

TaskManager.WebMVC/Controllers/UserController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Core;
using TaskManager.Core.Data;
using TaskManager.Core.Data.Repositories;
using TaskManager.Core.Models;

namespace TaskMaganer.Controllers
{
    public class UserController : DefaultController
    {
        private readonly UserRepository _userRepository;

        public UserController(TaskManagerContext context)
        {
            _userRepository = new UserRepository(context);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _userRepository.ListAllAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                await _userRepository.CreateAsync(user);
                ViewData["Mensagem"] = "Dados salvos com sucesso.";
            }
            else
            {
                ViewData["MensagemErro"] = "Ocorreu um erro ao salvar os dados.";
            }
            return View(user);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userRepository.GetByKeyAsync(id);
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(User user)
        {
            if (ModelState.IsValid)
            {
                await _userRepository.UpdateAsync(user);
                ViewData["Mensagem"] = "Dados alterados com sucesso.";
            }
            else
            {
                ViewData["MensagemErro"] = "Ocorreu um erro ao alterar os dados.";
            }
            return View(user);
        }

        public async Task<IActionResult> Details(int id)
        {
            var user = await _userRepository.GetByKeyAsync(id);
            return View(user);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var user = await _userRepository.GetByKeyAsync(id);
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(User user)
        {
            await _userRepository.DeleteAsync(user);
            return RedirectToAction("Index");
        }

    }
}

TaskManager.WebMVC/Views/Shared/_CommentDetails.cshtml
@model TaskManager.Core.Models.Comment


<dl class="row">

    <dt class="col-sm-2">Nome</dt>
    <dd class="col-sm-10">@Model.User.Name</dd>
    <dt class="col-sm-2">Criado em</dt>
    <dd class="col-sm-10">@Model.CreatedAt</dd>
    <dt class="col-sm-2">Comentário</dt>
    <dd class="col-sm-10">@Model.TextContent</dd>

</dl>

TaskManager.WebMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TaskManager.WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/dataTables.dataTables.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TaskManager.WebMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManager.WebMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Index">Tópicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Usuários</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tarefas</a>
                    </li>
                    <partial name="_LoginPartial"/>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - TaskManager.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/dataTables.min.js" asp-append-version="true"></script>
<script src="~/js/Funcoes.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManager.WebMVC/Views/Shared/_ListUsers.cshtml
@using TaskManager.Core.Models
@model IEnumerable<User>

<h2>Lista de Usuários</h2>

<table id="tabela" class="table table-striped">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Criado em</th>
            <th>Alterado em</th>            
        </tr>

    </thead>
    <tbody>
        @foreach (var userVm in Model)
        {
            <tr>
                <td>@userVm.Name</td>
                <td>@userVm.CreatedAt</td>
                <td>@userVm.UpdatedAt</td>                
            </tr>

        }
    </tbody>
</table>

TaskManager.WebMVC/Views/Shared/_TaskStatus.cshtml
@model TaskManager.Core.Models.MTask

@{
    string backgroundColor = ""; 
    string statusText = ""; 
    if (Model.Status == 1) 
    {
        backgroundColor = "red";
        statusText = "A fazer"; 
    }
    else if (Model.Status == 2) 
    {
        backgroundColor = "orange"; 
        statusText = "Fazendo"; 
    }
    else if (Model.Status == 3) 
    {
        backgroundColor = "green"; 
        statusText = "Concluído"; 
    }
}

<span style="display: inline-block; border-radius: 10%; border: 2px solid @backgroundColor; background: @backgroundColor; padding: 5px; color: white;">@statusText</span>

TaskManager.WebMVC/Views/Shared/_TaskTables.cshtml
@using TaskManager.Core.Enums
@model IEnumerable<TaskManager.Core.Models.MTask>

@{
    var todoTasks = Model.Where(t => t.Status == TaskStatusEnum.Todo.GetHashCode());
    var inProgressTasks = Model.Where(t => t.Status == TaskStatusEnum.InProgress.GetHashCode());
    var doneTasks = Model.Where(t => t.Status == TaskStatusEnum.Done.GetHashCode());
}

<h2>Tarefas A Fazer</h2>
<table id="table_todo"class="table table-striped">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in todoTasks) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                <span style="display: inline-block; border-radius: 10%; border: 2px solid @item.Topic.GetColorCode(); background: @item.Topic.GetColorCode(); padding: 5px;">@item.Topic.Name</span>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                <a href="@Url.Action("Details", "Task", new { id = item.Id })" class="btn btn-primary">Detalhes</a> |
                <a href="@Url.Action("Edit", "Task", new { id = item.Id })" class="btn btn-secondary">Editar</a> |
            </td>
        </tr>
    }
    </tbody>
</table>

<h2>Tarefas Em Andamento</h2>
<table id="table_doing"class="table table-striped">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in inProgressTasks) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                <span style="display: inline-block; border-radius: 10%; border: 2px solid @item.Topic.GetColorCode(); background: @item.Topic.GetColorCode(); padding: 5px;">@item.Topic.Name</span>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                <a href="@Url.Action("Details", "Task", new { id = item.Id })" class="btn btn-primary">Detalhes</a> |
                <a href="@Url.Action("Edit", "Task", new { id = item.Id })" class="btn btn-secondary">Editar</a> |
            </td>
        </tr>
    }
    </tbody>
</table>

<h2>Tarefas Em Concluídas</h2>
<table id="table_done" class="table table-striped">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in doneTasks) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                <span style="display: inline-block; border-radius: 10%; border: 2px solid @item.Topic.GetColorCode(); background: @item.Topic.GetColorCode(); padding: 5px;">@item.Topic.Name</span>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                <a href="@Url.Action("Details", "Task", new { id = item.Id })" class="btn btn-primary">Detalhes</a> |
                <a href="@Url.Action("Edit", "Task", new { id = item.Id })" class="btn btn-secondary">Editar</a> |
            </td>
        </tr>
    }
    </tbody>
</table>